---
title: "離岸風電產學官研網路"
output: 
  flexdashboard::flex_dashboard:
    theme: default
    css: JH.css
    social: menu
    source_code: embed 
    logo: mirdc48.png
    favicon: mirdc48.png
runtime: shiny
---

```{r}
pacman::p_load(magrittr,shiny,shinyWidgets,shinythemes,flexdashboard)
pacman::p_load(visNetwork,reshape2,stringr,RColorBrewer)
pals16 = c(brewer.pal(12,"Set3"),brewer.pal(8,"Set1")[1:4])
load("data/C20.rdata")
s0 = c(0, table(E$class) %>% cumsum %>% as.integer)
s9 = table(E$class)
subcls = sort(unique(E$sub_class[E$class=="ORG"]))
```

詳細設定 {data-icon="fa-cogs"}
=====================================================

Column {data-width=25%}
-------------------------------------
### Input 
```{r}
chooseSliderSkin("Modern")
sliderInput("K", "顯示連結(%)", 0, 1, 0.2, 0.01)

prettyRadioButtons(
  "Unit", "段落", choices = list("句"=1, "段"=2, "篇"=3),
  selected = 1, inline=T, icon=icon("check"), 
  status="success", animation="jelly")

prettyRadioButtons(
  "Cor", "關係", 
  # choices = list("Co-Occur"=0, "Corr"=3),
  choices = list("Co-Occur"=0, "Corr"=1),
  selected = 1, inline=T, icon=icon("check"), 
  status="success", animation="jelly")

awesomeCheckboxGroup(
   "Classes", "類別", 
   choices = unique(E$class),
   selected = unique(E$class),
   inline = TRUE, status="success")

awesomeCheckboxGroup(
   "Subs", "公司類別", 
   choices = subcls,
   selected = subcls,
   inline = TRUE, status="success")

sliderInput("COUNTRY",     "Country",  1, s9[1],  c(4,7), 1)
sliderInput("FARM",       "WindFARM",  1, s9[2],  c(2,5), 1)
sliderInput("FINANCE",     "Finance",  1, s9[3],  c(1,4), 1)
sliderInput("GOV",       "Govn.Adm.",  1, s9[4],  c(3,6), 1)
sliderInput("INST",    "Institution",  1, s9[5],  c(3,6), 1)
sliderInput("KWORD",      " Keyword",  1, s9[6],  c(3,6), 1)
sliderInput("LOC",        "Location",  1, s9[7],  c(3,4), 1)
sliderInput("ORG",        "Company",   1, s9[8],  c(3,9), 1)
sliderInput("TERM",   "Terminology",   1, s9[9],  c(1,4), 1)
sliderInput("UNIV",     "University",  1, s9[10], c(1,4), 1)
sliderInput("VESSEL",       "Vessel",  1, s9[11], c(1,4), 1)

```


Column {data-width=75%}
-------------------------------------
### visNetwork
```{r}
vis_network = function() {
  s1 = rbind(
  COUNTRY=input$COUNTRY, FARM=input$FARM, FINANCE=input$FINANCE, 
  GOV=input$GOV, INST=input$INST, KWORD=input$KWORD, LOC=input$LOC,
  ORG=input$ORG, TERM=input$TERM, UNIV=input$UNIV, VESSEL=input$VESSEL)

  classes = which(unique(E$class) %in% input$Classes)
  si = do.call(c,lapply(classes, function(i) s0[i]+(s1[i,1]:s1[i,2]) ))
  si = setdiff(si, which(E$class == "COM" & ! E$sub_class %in% input$Subs))
  i = as.integer(input$Unit)
  if(input$Cor=="1") x = CR[[i]][si,si]
  else x = CO[[i]][si,si]

  tt = with(E, sprintf(
    "<b>%s</b>: %s<br>(%s,%s,%d)", name[si],tooltip[si], 
    class[si], sub_class[si], freq[si])
    ) %>% str_replace(",NA,", ",")
  nodes = data.frame(
    id = 1:nrow(x), label=E$name[si], title=tt,
    group=E$class[si], value=sqrt(E$freq[si]), 
    shape="square", stringsAsFactors=F)

  colnames(x) = rownames(x) = 1:nrow(x)
  x[lower.tri(x,T)] = 0
  x = subset(melt(x), value > 0)

  K = 1 - input$K
  links = subset(x, value >= quantile(value, K))
  links$value = sqrt(links$value)
  colnames(links)[1:2] = c("from","to")
  i = 1:nrow(nodes) %in% unique(c(links[,1], links[,2]))
  nodes$hidden = !i; nodes$physics = i

  visNetwork(nodes, links) %>%
    visPhysics("forceAtlas2Based") %>%
    visEdges(color=list(opacity=0.4)) %>%
    visOptions(highlightNearest=T) %>% 
    visGroups(groupname="COUNTRY", color=pals16[1]) %>% 
    visGroups(groupname="FARM", color=pals16[2]) %>% 
    visGroups(groupname="FINANCE", color=pals16[3]) %>% 
    visGroups(groupname="GOV", color=pals16[4]) %>% 
    visGroups(groupname="INST", color=pals16[5]) %>% 
    visGroups(groupname="KWORD", color=pals16[6]) %>% 
    visGroups(groupname="LOC", color=pals16[7]) %>% 
    visGroups(groupname="ORG", color=pals16[8]) %>% 
    visGroups(groupname="TERM", color=pals16[9]) %>% 
    visGroups(groupname="UINV", color=pals16[10]) %>% 
    visGroups(groupname="VESSEL", color=pals16[11]) %>% 
    visLegend(width=0.1, stepY=100, useGroups=F, addNodes=data.frame(
      label=unique(E$class), shape='square', color=pals16[1:11])
      )

  }

renderVisNetwork( vis_network() )
```

社會網路圖 {data-icon="fa-share-alt"}
=====================================================
```{r}
renderVisNetwork( vis_network() )
```
